version: '3.8'

services:
  portal-backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=insecure_secret_key_for_lab
    volumes:
      - ./backend:/app
    networks:
      - portal_network

  portal-db:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - portal_network

networks:
  portal_network:
    driver: bridge
